baseURL = "https://montrealcup.ca/"
title = "Montreal Cup"
author = "nikkimoore"
languageCode = "fr"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
favicon = "static/favicon.io"

[params]

  mainSections = ['blog']

  googleFonts = true

  showBlog = false

  [params.logo]
    main = "img/logo/logo1.svg"
    alt = "Montreal Cup Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-17"

  [params.site]
    name = "Montreal Cup"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Offical website for the Montreal Cup"
    meta_og_title = "Montreal Cup"
    meta_og_type = "website"

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'EN'

  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'FR'
    
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "about"
    weight = 1

  [[menu.main]]
    identifier = "contact-us"
    name = "Contact"
    url = "contact-us"
    weight = 4

  [[menu.main]]
    identifier = "sponsors"
    name = "Sponsors"
    url = "sponsors"
    weight = 2

  [[menu.main]]
    identifier = "fundraising"
    name = "Fundraising events"
    url = "fundraising"
    weight = 3
    
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files