baseURL = "https://montrealcup.ca/"
title = "Montréal Cup 2024"
author = "nikkimoore"
languageCode = "fr"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

googleAnalytics = "UA-12345678-1"

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1

[params]

  mainSections = ['blog']

  googleFonts = true

  showBlog = false

  Description = "Official website of the Montréal Cup. September 6-8 2024. Register now!"

  [params.logo]
    main = "img/logo/logo1.svg"
    alt = "Montreal Cup Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-17"

  [params.site]
    name = "Montreal Cup"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "A website for the Montreal Cup"
    meta_og_title = "Montreal Cup"
    meta_og_type = "website"

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'EN'
    robots = "index,follow"

  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'FR'
    robots = "index,follow"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "sponsors"
    name = "Sponsors"
    url = "/sponsors/"
    weight = 5

  [[menu.main]]
    identifier = "course"
    name = "Course"
    url = "/course/"
    weight = 4

  [[menu.main]]
    identifier = "contact-us"
    name = "Contact"
    url = "/contact-us/"
    weight = 6

  [[menu.main]]
    identifier = "register"
    name = "Register"
    url = "https://solo-inline.com/en/products/inscription-inline-montreal-cup?variant=45511118258388"
    weight = 2

  [[menu.main]]
    identifier = "schedule"
    name = "Schedule"
    url = "/schedule/"
    weight = 3
    
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files